landscape.yaml split
gardener/landscape-setup-template pull request #13
Opened 2018-06-08 11:59 UTC by Diaphteiros

`landscape.yaml` is splitted into `landscape_base.yaml` and `user_config.yaml`.

2018-06-08 16:02 UTC, msohn reviewed
will you also address the other comments I gave ?

2018-06-08 16:02 UTC, msohn commented on landscape_config.yaml
> +    hash: "$2a$10$JIKb36h2oM5pVAvvM/EniemkQJhCtdmmsVamyRmNVJhCyOlTY72uu" # example hash for password "password"
I would write this like you did elsewhere, and remove the unnecessary comments:

 email: \<email address>\>
 hash: \<bcrypted password\>
 username: \<user name\>
 userID: \<UUID\>

2018-06-11 13:42 UTC, Diaphteiros commented on user_config.yaml
> +misc:
I agree, but I didn't find a better name for this / a better node to group the values

2018-06-11 13:51 UTC, Diaphteiros commented on landscape_base.yaml
> +        domain: (( "internal." clusters.dns.domain_name ))
It concatenates "internal." with the value of the clusters.dns.domain_name node.

2018-06-11 14:00 UTC, Diaphteiros commented on landscape_base.yaml
> +# that is assumed to be independent of the user configuration.
Hm, I googled a bit and it seems that "independent from" is mainly used when talking about countries or people, while "independent of" is better in most other cases.

2018-06-12 15:12 UTC, msohn requested changes

2018-06-12 15:12 UTC, msohn commented on landscape_config.yaml
> +  # Email address used for ACME registration
link to https://en.wikipedia.org/wiki/Automated_Certificate_Management_Environment ?

2018-06-12 15:12 UTC, msohn commented on landscape_config.yaml
> +    region: "eu-west-1"
can we refer to the key aws_region defined above ?

2018-06-12 15:12 UTC, msohn commented on landscape_config.yaml
> +    region: "<region name>"
can we refer to the key aws_region defined above ?

2018-06-12 15:12 UTC, msohn commented on README.md
this commit can be squashed into 3c347bab0e620eeced73969743aa099f764835e6

2018-06-12 15:12 UTC, msohn commented on landscape_config.yaml
>      # use htpasswd to create password entries
submodule update should be done in the commit doing the split of the landscape.yaml file

2018-06-14 14:42 UTC, msohn requested changes
the ./deploy_gardener.sh could print the URLs to open to accept self-signed certs and open the Gardener dashboard, this way the user doesn't need to type the URL and can open it directly

2018-06-14 14:42 UTC, msohn commented on README.md
> +# clone git repo with submodules
remove this comment, instead start with
 \# setup

2018-06-14 14:42 UTC, msohn commented on README.md
> +
remove unnecessary blank lines

2018-06-14 14:42 UTC, msohn commented on README.md
> +
\# teardown

and leave out the comments

2018-06-15 12:11 UTC, msohn approved these changes

2018-06-15 12:11 UTC, merged